### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by fedzav7** [pfefferle/atom-php-cs-fixer#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Unknown Windows Version
**Thrown From**: [php-cs-fixer](https://github.com/pfefferle/atom-php-cs-fixer) package, v2.1.0
### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At child_process.js:1145

Error: spawn UNKNOWN
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at Object.module.exports.PhpCsFixer.fix (C:\Users\Fedzav\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:57:15)
  at atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix (C:\Users\Fedzav\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:27:84)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLOListElement.elemData.handle (C:\Users\Fedzav\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4116:28)

```
### Commands

```
     -3:16 command-palette:toggle (atom-text-editor.editor)
     -3:13.6.0 project-manager:toggle (atom-text-editor.editor.mini)
     -3:07.8.0 command-palette:toggle (atom-text-editor.editor)
     -3:05.2.0 php-cs-fixer:fix (atom-text-editor.editor)
     -0:58.7.0 core:save-as (atom-text-editor.editor)
     -0:54.2.0 snippets:available (atom-text-editor.editor)
     -0:51.7.0 project-manager:toggle (atom-text-editor.editor.mini)
     -0:50.4.0 command-palette:toggle (atom-text-editor.editor.mini)
     -0:45.5.0 php-cs-fixer:fix (atom-text-editor.editor.mini)
     -0:21.4.0 core:backspace (atom-text-editor#php-cs-fixer.executablePath.editor.mini)
     -0:13.8.0 command-palette:toggle (atom-text-editor.editor)
     -0:11.4.0 php-cs-fixer:fix (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "dracula-theme"
    ],
    "disabledPackages": [
      "atom-beautifier",
      "autoclose-html",
      "linter"
    ]
  },
  "php-cs-fixer": {
    "executablePath": "C:\\php-cs-fixer.phar",
    "level": "psr1"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.12.0
color-picker, v1.7.0
dracula-theme, v0.7.6
emmet, v2.3.8
minimap, v4.7.6
php-cs-fixer, v2.1.0
project-manager, v1.15.5
Remote-FTP, v0.6.2
spacegray-dark-ui, v0.8.0

# Dev
No dev packages
```

**Comment by pfefferle** [comment]
Have you added the path to your `php-cs-fixer` installation?

**Comment by fedzav7** [comment]
The error is on the php-cs-fixer package not in the beautify one, and i 
have put both directories on settings.

Simply "C:\php-cs-fixer.phar"

THanks for the help

Il 27/04/2015 17:54, Matthias Pfefferle ha scritto:

**Comment by pfefferle** [comment]
I released a new version and replaced "spawn" with the more Windows friendly "BufferedProcess"... Can you test it once again?

**Comment by fedzav7** [comment]
ok next monday i will check, thank you for the help :)

2015-04-29 22:43 GMT+02:00 Matthias Pfefferle notifications@github.com:
