### ISSUE TITLE
php-cs-fixer got broken for linux user after fixing the issue 6 for windows user

### ISSUE THREAD

**Issue by mappedinn** [pfefferle/atom-php-cs-fixer#31]
Hi, 

I use Linux Ubuntu 16.04. I have well installed php-cs-fixer for atom 1.9.8.

```
$ php-cs-fixer
PHP CS Fixer version 1.11.6 by Fabien Potencier

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  fix          Fixes a directory or a file
  help         Displays help for a command
  list         Lists commands
  readme       Generates the README content, based on the fix command help
  self-update  Update php-cs-fixer.phar to the latest version.
  selfupdate   Update php-cs-fixer.phar to the latest version.
```

The problem comes with config of php-cs-fixer with atom. In fact, package requires:
- a PHP Executable path (which is by defaut `php`) (for linux user it must be empty which is not possible with actual version of the  package) (see isse #6 )
- a PHP-CS fixer Executable path (which is simply for linux user `php-cs-fixer` _(without the use of PHAR file)_)

Consequently, when I run php-cs-fixer from atom I get this error: **Could not open input file: php-cs-fixer**.

I can generate this error message with this console command:

```
php php-cs-fixer fix Class.php 
    Could not open input file: php-cs-fixer
```

So, can you @pfefferle make `PHP Executable path` optional (not compulsory)???

thanks,

**Comment by mappedinn** [comment]
@pfefferle  May be we just should change the config here https://github.com/pfefferle/atom-php-cs-fixer/blob/master/lib/php-cs-fixer.coffee#L12 as follows:

```
phpExecutablePath:
  title: 'PHP executable path'
  type: 'string'
  default: ''   # in stead of 'php'
  description: 'the path to the `php` executable'
```

**Comment by mappedinn** [comment]
I changed the `lib/php-cs-fixer.coffee` as I mentionned earlier. Then, I select the text on which I will run the php-cs-fixer and below is the error I am getting...

Do you think @pfefferle that it would better to create a phar file for php-cs-fixer?

---

**Atom Version**: 1.9.8
**System**: Ubuntu 16.04.1
**Thrown From**: [php-cs-fixer](https://github.com/pfefferle/atom-php-cs-fixer) package, v2.5.9

### Stack Trace

Uncaught TypeError: Bad argument

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:379:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at Object.module.exports.PhpCsFixer.fix (/home/amine/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:125:19)
    at atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix (/home/amine/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:72:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1110:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

### Commands

```
     -4:54.1.0 settings-view:open (atom-pane.pane.active)
     -4:08.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:05.7.0 php-cs-fixer:fix (atom-text-editor.editor.is-focused)
  3x -3:05.4.0 core:backspace (atom-text-editor#php-cs-fixer.fixers.editor.mini.is-focused)
     -2:57 core:select-all (atom-text-editor.editor.is-focused)
     -2:54.1.0 php-cs-fixer:fix (atom-text-editor.editor.is-focused)
     -0:52.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:00.1.0 php-cs-fixer:fix (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "projectHome": "/home/amine/NetBeansProjects"
  },
  "php-cs-fixer": {
    "executeOnSave": false,
    "fixers": "fix",
    "level": "symfony",
    "showInfoNotifications": true
  }
}
```

### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.9 (active)
atom-beautify, v0.29.10 (inactive)
atom-symfony2, v0.2.1 (active)
php-cs-fixer, v2.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mappedinn** [comment]
I managed to download `php-cs-fixer.phar` from https://github.com/FriendsOfPHP/PHP-CS-Fixer and I put it in the folder `~/.composer/` so that:
- a PHP Executable path is `php`
- a PHP-CS fixer Executable path is: `~/.composer/php-cs-composer.phar`

But now I am getting this error: **Could not open input file: ~/.composer/php-cs-fixer.phar**

So what's wrong??

For you information, running the console `php ~/.composer/php-cs-composer.phar Class.php` command is successful.

Thanks in advance

**Comment by pfefferle** [comment]
It seems that Atom has Problems with the home folder (~) please try the complete path to the php-cs-fixer executable (if it is the phar file or the php file, shouldn't make a difference): `/home/{your name}/.composer/{php-cs-fixer path}`

**Comment by pfefferle** [comment]
BTW: I also use the absolute path to my php executable: `/use/bin/php`

**Comment by pfefferle** [comment]
My Settings:

![bildschirmfoto 2016-08-12 um 15 17 01](https://cloud.githubusercontent.com/assets/2373/17623349/dce602b6-609f-11e6-820c-692e2c0b1a83.png)

**Comment by mappedinn** [comment]
Problem solved!!! 
I have a symfony project working on, so advise me to use the **symfony** level or the **psr2**?

Thanks...
