### ISSUE TITLE
spawn php-cs-fixer ENOENT

### ISSUE THREAD

**Issue by oleche** [pfefferle/atom-php-cs-fixer#4]
Error: spawn php-cs-fixer ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)

When trying to run the atom beautifier

**Comment by pfefferle** [comment]
Are you sure this is a problem with this plugin? Atom beautify is also using the php-cs-fixer https://atom.io/packages/atom-beautify
