### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by dtomasch** [pfefferle/atom-php-cs-fixer#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [php-cs-fixer](https://github.com/pfefferle/atom-php-cs-fixer) package, v2.2.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at Object.module.exports.PhpCsFixer.fix (/Users/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:61:19)
  at atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix (/Users/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:27:84)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -3:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -2:59.8.0 core:close (atom-text-editor.editor.is-focused)
     -2:52.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -2:21.2.0 fuzzy-finder:toggle-buffer-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:18.8.0 core:move-left (atom-pane.pane.active)
  2x -2:13.6.0 php-cs-fixer:fix (atom-pane.pane.active)
     -1:54.4.0 atom-beautify:beautify-editor (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -1:21.5.0 core:paste (atom-text-editor#php-cs-fixer.executablePath.editor.mini.is-focused)
     -1:19.8.0 core:save (atom-text-editor#php-cs-fixer.executablePath.editor.mini.is-focused)
     -1:18.1.0 core:select-all (ul.list-inline.tab-bar.inset-panel)
     -1:12.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:09.2.0 php-cs-fixer:fix (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close.has-stack)
     -0:02.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.5.0 php-cs-fixer:fix (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-less",
      "language-shellscript",
      "language-sql",
      "language-todo",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "release-notes",
      "close-tags",
      "php-class-tree"
    ]
  },
  "php-cs-fixer": {
    "executablePath": "/Users/username/Downloads/php-cs-fixer.phar"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
color-picker, v2.0.4
emmet, v2.3.10
linter, v0.12.7
linter-csslint, v0.0.13
linter-php, v0.0.15
linter-scss-lint, v1.0.4
minimap, v4.10.0
php-cs-fixer, v2.2.0
tag, v0.3.0

# Dev
No dev packages
```

**Comment by pfefferle** [comment]
Have you tried to run `/Users/dtomasch/Downloads/php-cs-fixer.phar` at your command line? does this work? Perhaps you have to try `php /Users/dtomasch/Downloads/php-cs-fixer.phar`

**Comment by dtomasch** [comment]
I had problems with Atom Beautify and while working to debug that, looks like it just wasn't installed correctly. I went with this specific sequence and it works now: 

Install PHP-CS-Fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer)
Run:
$ curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer
$ sudo chmod a+x php-cs-fixer
$ sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

**Comment by pfefferle** [comment]
I am glad you got it running finally :)
