### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by x7peeps** [pfefferle/atom-php-cs-fixer#64]
today i use my atom-beautiful to fixer the PHP formate but i got this error followed:
![image](https://cloud.githubusercontent.com/assets/9640837/26274112/4faa8018-3d74-11e7-9b15-a71758fe2acb.png)

`
E:\Brian Work\MyWeb Project\\test.php11:1
CRLFUTF-8PHP
Could not find 'php'. The program may not be installed.
See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.
Hide Stack Trace
Error: Could not find 'php'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/42161/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:231:14)
    at file:///C:/Users/42161/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:331:22
    at tryCatcher (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\42161\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

how do i do to fix this problem?

**Comment by x7peeps** [comment]
![image](https://cloud.githubusercontent.com/assets/9640837/26274211/e648e332-3d76-11e7-9cf9-babab136b3a5.png)
![image](https://cloud.githubusercontent.com/assets/9640837/26274214/07000600-3d77-11e7-8e71-eaf0e1f001ef.png)

**Comment by pfefferle** [comment]
this is not the atom-beautify repo, sorry!
