### ISSUE TITLE
Could not find 'C:\WINDOWS\system32\php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by girishandroid** [pfefferle/atom-php-cs-fixer#72]
See C:\WINDOWS\system32\php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'where.exe C:\WINDOWS\system32\php-cs-fixer' in your CMD prompt returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'C:\WINDOWS\system32\php-cs-fixer'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/akhar/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:10)
    at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/akhar/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
    at file:///C:/Users/akhar/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
    at tryCatcher (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\akhar\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by pfefferle** [comment]
Sorry, this is not the repo for the atom-beautify
